#+PROPERTY: header-args :tangle yes
Script to setup arch linux.
* Varables for what to install
#+begin_code sh
#!/bin/sh
fonts="noto-fonts"
clitools="tmux git neovim"
audio="pipewire pipewire-jack"
filemanagment="pcmanfm "
#+end_lang
** Username
#+begin_lang sh
username="rafal"
#+end_lang
* Check if running as root
If not running as root exit.
#+begin_lang sh
if [ "$(whoami)" = "root" ]
then
printf %s "Not root! run this as root\n";
exit 1;
fi
#+end_lang
* Basic system setup
** Replace default /bin/sh with dash
#+begin_lang sh
pacman -S dash;
rm /bin/sh;
ln -s "$(which dash)" "/bin/sh";
#+end_lang

** Install doas and remove sudo if installed

and allow wheel group members to execute as root.
#+begin_lang sh
pacman -R sudo
pacman -S doas
echo "permit persist :wheel as root" >> /etc/doas.conf;
ln -s "$(which doas)" /bin/sudo;
#+end_lang

* Add user
** Create user
#+begin_lang sh
useradd --create-home --user-group -groups wheel "$username";
#+end_lang
** Set up password for the user
#+begin_lang sh
echo "Set password for $username"
passwd "$username"
#+end_lang
** TODO Set up git bare repo for config files


** Create directories
#+begin_lang sh
su -c "mkdir ~/Desktop ~/Downloads ~/Documents" "$username" &&
#+end_lang
* Intall specifics
** Doom eamcs
Dependecies.
#+begin_lang sh
pacman -S "ripgrep emacs fd git" &&
su -c "git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d &&
    ~/.emacs.d/bin/doom install" "$username"
#+end_lang sh



* TODO Set up desktop enviroment
